### PR TITLE
Add flatstr() call to write() method

### PR DESCRIPTION
**Pull request by KurtPattyn**

### CODE REVIEW

**Comment by mcollina** [comment]
I'm getting slightly different numbers than yours on Node 10:

This branch:

```
$ node bench.js
benchSonic*1000: 834.799ms
benchSonic4k*1000: 792.515ms
```

master:

```
$ node bench.js
benchSonic*1000: 684.098ms
benchSonic4k*1000: 649.790ms
```

And that's the actual reason why we are not doing this in the first place.

Have you tried if this improves pino benchmarks at all?

**Comment by KurtPattyn** [comment]
Yes I did. I will perform your tests and show you the ones I did. I’ll come back once I get home.

**Comment by KurtPattyn** [comment]
Hi Matteo,

that bench.js is only testing 'plain' text (i.e. 'hello world'). Plain text is actually slower with `flatstr()`.
That is the reason I asked to include the `flatstr()` call in pino instead of in sonic-boom.
You indicated that sonic-boom is actually meant as a backend for pino; so, I included that flatstr() call there.
You only see a boost when testing with 'concatenated' strings (as they actually come from Pino), but as sonic-boom is meant solely as a backend to pino, testing with plain text doesn't matter.
See issue: https://github.com/mcollina/sonic-boom/issues/19#issue-387248348
In the table there, you can actually see that 'plain' text performance is worse, but that concatenated performance is `boosted` ;-)

I definitely did tests with pino to see that the performance impact was considerate.
I will add another comment to show you the numbers.

**Comment by mcollina** [comment]
As part of this PR, can you please amend our benchmarks here?

**Comment by KurtPattyn** [comment]
@mcollina Will do :-)
In the mean time, here are the benchmark results for pino:
image

**Comment by mcollina** [comment]
@KurtPattyn any updates on this?

**Pull request closed without merging**
